### ISSUE TITLE
Mixins are deprecated in react 0.14

### ISSUE THREAD

**Issue by pke** [jasonslyvia/react-lifecycle#1]
Do you have any plans to convert the mixin to a function that could be used like:
`lifecycle(MyComponent)`

**Comment by jasonslyvia** [comment]
I don't suppose mixins are deprecated only if you insist using the `class` syntax. However, there're quite a few mixins decorators that allow you take advantage of existing mixins using `class`.
1. [https://github.com/timbur/react-mixin-decorator](https://github.com/timbur/react-mixin-decorator)
2. [https://github.com/jayphelps/core-decorators.js/blob/master/src/mixin.js](https://github.com/jayphelps/core-decorators.js/blob/master/src/mixin.js)
